kind: Service
apiVersion: v1
metadata:
  name: restvirt-csi-controller
  namespace: kube-system
  labels:
    app: restvirt-csi-controller
spec:
  selector:
    app: restvirt-csi-controller
  clusterIP: None
