kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: restvirt-sc
provisioner: restvirt.verbit.io
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restvirt-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: restvirt-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: restvirt-claim